### ISSUE TITLE
5-maps.me: Bonus - map component test

### ISSUE THREAD

**Issue by YmerejRedienhcs** [mjuniper/ambitious-arcgis-app-2018#33]
I occasionally got test results like this:

```
Expected: | "/items?q=water"
-- | --
"/"
"/items?q=water"
at Object.<anonymous> (http://localhost:7357/assets/tests.js:23:17)     at <anonymous>
```

```
TEST'EM 'SCRIPTS!
Open the URL below in a browser to connect.
http://localhost:7357/
━━━━━━━━━━━━━━┓
     Chrome   ┃
   35/36 ✘    ┃
              ┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Acceptance | smoke: smoke-test
    ✘ failed
            at Object.<anonymous> (http://localhost:7357/assets/tests.js:23:17)
            at <anonymous>
         expected /items?q=water
         actual /
    ✘ failed
            at Object.<anonymous> (http://localhost:7357/assets/tests.js:25:17)
            at <anonymous>
         expected 10
[Press ENTER to run tests; q to quit; p to pause]
```

If I forced the tests to run again (say by saving a source file), then the same tests would run and the tests would all pass.

**Comment by tomwayson** [comment]
Bummer.

I assume you already have this in your smoke test right:

```js
// force the test to wait a bit longer
// this should not be necessary but appears to be... _sometimes_
let flag = false;
later(() => flag = true, 500);
await waitUntil(() => flag);
```

**Comment by YmerejRedienhcs** [comment]
Shucks, I was hoping that I _had_ neglected to follow that step, but unfortunately, I had, and it still fails intermittently.

![image](https://user-images.githubusercontent.com/521773/36940598-05cf6be8-1f14-11e8-8731-f512a15657ab.png)

I tried running again a few times just now, and it still fails sometimes.  7 out of 20 times just now (35%).

**Comment by tomwayson** [comment]
😦
